### ISSUE TITLE
Position of Mixins within Styles

### ISSUE THREAD

**Issue by ghost** [adamhughes86/CCF1#3]
Just a quick question regarding mixins. In which order do mixins appear in the style declarations, in the CCF1 Standards the mixins appear at the top under includes, but where would a the following mixin appear?  

@include transform(rotate(45deg));

Would it still be under the includes, or would it come under the visual group of declarations?

**Comment by adamhughes86** [comment]
I'll develop out this part of the spec but I'm thinking that mixins which only include one type of style and are providing a fallback option should go in place of their output declaration. Any mixin that has multiple styles (e.g. a mixin that provides a base widget style) should be placed after the extends and before the declarations.

I'll work on making this sound clearer
